### ISSUE TITLE
Invalid characters cause error in HEX detection

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_hmib#28]
```
2021/09/01 07:45:11 - CMDPHP PHP ERROR Backtrace: (/plugins/hmib/poller_hmib.php[139]:checkHost(), /plugins/hmib/poller_hmib.php[577]:collect_hrStorage(), /plugins/hmib/poller_hmib.php[959]:collectHostIndexedOid(), /plugins/hmib/poller_hmib.php[715]:cacti_snmp_walk(), /plugins/hmib/snmp.php[413]:format_snmp_string(), /plugins/hmib/snmp.php[459]:hexdec(), CactiErrorHandler())
2021/09/01 07:45:11 - ERROR PHP DEPRECATED in Plugin 'hmib': Invalid characters passed for attempted conversion, these have been ignored in file: /var/www/localhost/htdocs/cacti/plugins/hmib/snmp.php on line: 459
```

**Comment by netniV** [comment]
OK, so this is failing because the string contains a colon but it's not a HEX character, ie `FW: Would error` but `FA: Would not`.  The reason being, the first example has just two characters before the colon so it attempts to convert it to hex without checking it matches hex.  The second part of the string would be over 2 characters so the code correctly says, nope that ain't a hex string.  In the second example, the FA is a valid HEX combo so it passes without error, then it says again, nope that's too long for hex.

The fix for this would be to use a preg_match so i'm going to apply that and you should then pull the latest version of the code.  See https://regex101.com/r/V2qnlP/1
